#!/usr/bin/env node
/**
 * 👑 alpha-bot: census.js
 *
 * Conducts a full fleet census:
 *   - All bot workflow files in .github/workflows/
 *   - All bot script directories in scripts/
 *   - All docs generated by bots
 *   - Bot identity matrix (name, emoji, domain, trigger, scripts)
 *
 * Output: docs/fleet-census.json
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT      = path.resolve(__dirname, '..', '..');
const WORKFLOWS = path.join(ROOT, '.github', 'workflows');
const SCRIPTS   = path.join(ROOT, 'scripts');
const DOCS      = path.join(ROOT, 'docs');

fs.mkdirSync(DOCS, { recursive: true });

// ── Known bot fleet manifest ──────────────────────────────────────────────────
const KNOWN_BOTS = [
  // Division I — Build & Package
  { name: 'organism-build-bot',       emoji: '🧬', domain: 'Extension Packaging',      workflow: 'organism-build-bot.yml',       scriptDir: 'build-bot',       division: 'Build & Package'      },
  { name: 'organism-sdk-bot',         emoji: '📦', domain: 'SDK Packaging',            workflow: 'organism-sdk-bot.yml',         scriptDir: 'sdk-bot',         division: 'Build & Package'      },
  { name: 'organism-release-bot',     emoji: '🚀', domain: 'Production Releases',      workflow: 'organism-release-bot.yml',     scriptDir: null,              division: 'Build & Package'      },
  // Division II — Validate & Test
  { name: 'organism-neural-bot',      emoji: '🧠', domain: 'Deep AI Architecture',     workflow: 'organism-neural-bot.yml',      scriptDir: 'neural-bot',      division: 'Validate & Test'      },
  { name: 'organism-protocol-bot',    emoji: '🔬', domain: 'Protocol Integrity',       workflow: 'organism-protocol-bot.yml',    scriptDir: 'protocol-bot',    division: 'Validate & Test'      },
  { name: 'organism-test-bot',        emoji: '🧪', domain: 'Cross-Matrix Testing',     workflow: 'organism-test-bot.yml',        scriptDir: null,              division: 'Validate & Test'      },
  { name: 'organism-sandcastle-bot',  emoji: '🏰', domain: 'Sandboxed BTL Pipeline',  workflow: 'organism-sandcastle-bot.yml',  scriptDir: 'sandcastle-bot',  division: 'Validate & Test'      },
  { name: 'organism-visual-bot',      emoji: '📸', domain: 'Visual Regression',        workflow: 'organism-visual-bot.yml',      scriptDir: 'visual-bot',      division: 'Validate & Test'      },
  // Division III — Secure & Monitor
  { name: 'organism-sentinel-bot',    emoji: '🛡️', domain: 'Security',                 workflow: 'organism-sentinel-bot.yml',    scriptDir: 'sentinel-bot',    division: 'Secure & Monitor'     },
  { name: 'organism-deps-bot',        emoji: '🔄', domain: 'Dependency Health',        workflow: 'organism-deps-bot.yml',        scriptDir: 'deps-bot',        division: 'Secure & Monitor'     },
  { name: 'organism-crawler-bot',     emoji: '🕷️', domain: 'Organism Mapper',          workflow: 'organism-crawler-bot.yml',     scriptDir: 'crawler-bot',     division: 'Secure & Monitor'     },
  // Division IV — Document & Report
  { name: 'organism-docs-bot',        emoji: '📚', domain: 'Auto-Documentation',       workflow: 'organism-docs-bot.yml',        scriptDir: 'docs-bot',        division: 'Document & Report'    },
  // Division V — Deploy & Operate
  { name: 'organism-deploy-bot',      emoji: '🌐', domain: 'Deployment',               workflow: 'organism-deploy-bot.yml',      scriptDir: 'deploy-bot',      division: 'Deploy & Operate'     },
  // Division VI — Learn & Evolve
  { name: 'organism-learning-bot',    emoji: '🎓', domain: 'Continuous Learning',      workflow: 'organism-learning-bot.yml',    scriptDir: 'learning-bot',    division: 'Learn & Evolve'       },
  { name: 'organism-economy-bot',     emoji: '💰', domain: 'Marketplace Analytics',    workflow: 'organism-economy-bot.yml',     scriptDir: 'economy-bot',     division: 'Learn & Evolve'       },
  // Division VII — Command & Control
  { name: 'organism-alpha-bot',       emoji: '👑', domain: 'Fleet Command',            workflow: 'organism-alpha-bot.yml',       scriptDir: 'alpha-bot',       division: 'Command & Control'    },
  { name: 'organism-governance-bot',  emoji: '🌐', domain: 'Atlas Governance Cycle',  workflow: 'organism-governance-bot.yml',  scriptDir: 'governance',      division: 'Command & Control'    },
];

// ── Census each bot ───────────────────────────────────────────────────────────
const census = [];

console.log('');
console.log('👑 organism-alpha-bot: Fleet Census');
console.log('══════════════════════════════════════════════════════════');

let healthy = 0;
let degraded = 0;

for (const bot of KNOWN_BOTS) {
  const workflowPath = path.join(WORKFLOWS, bot.workflow);
  const scriptDirPath = bot.scriptDir ? path.join(SCRIPTS, bot.scriptDir) : null;

  const hasWorkflow   = fs.existsSync(workflowPath);
  const hasScriptDir  = scriptDirPath ? fs.existsSync(scriptDirPath) : null;

  // Count scripts if dir exists
  let scriptCount = 0;
  let scripts = [];
  if (hasScriptDir) {
    scripts = fs.readdirSync(scriptDirPath).filter(f => f.endsWith('.js'));
    scriptCount = scripts.length;
  }

  // Read workflow for trigger type
  let trigger = 'unknown';
  let workflowSize = 0;
  if (hasWorkflow) {
    const src = fs.readFileSync(workflowPath, 'utf8');
    workflowSize = src.length;
    if (src.includes('schedule:')) trigger = 'scheduled + push';
    else if (src.includes('push:')) trigger = 'push';
    else if (src.includes('tags:')) trigger = 'tags (v*)';
    else trigger = 'manual';
  }

  const status = hasWorkflow ? 'healthy' : 'degraded';
  if (status === 'healthy') healthy++; else degraded++;

  const statusIcon = status === 'healthy' ? '✓' : '✗';
  const scriptInfo = scriptDirPath
    ? (hasScriptDir ? `${scriptCount} scripts` : 'no script dir')
    : 'inline scripts';
  console.log(`  ${statusIcon} ${bot.emoji} ${bot.name} [${scriptInfo}]`);

  census.push({
    ...bot,
    hasWorkflow,
    hasScriptDir,
    scripts,
    scriptCount,
    trigger,
    workflowSize,
    status,
  });
}

console.log('');
console.log(`  Fleet: ${healthy} healthy, ${degraded} degraded (${KNOWN_BOTS.length} total bots)`);
console.log('');

// ── Discover any unknown workflow files ───────────────────────────────────────
const allWorkflows = fs.readdirSync(WORKFLOWS).filter(f => f.startsWith('organism-') && f.endsWith('.yml'));
const knownFiles   = new Set(KNOWN_BOTS.map(b => b.workflow));
const unknownBots  = allWorkflows.filter(f => !knownFiles.has(f));
if (unknownBots.length > 0) {
  console.log(`  ⚠ Unknown bot workflows detected: ${unknownBots.join(', ')}`);
}

// ── Write census JSON ─────────────────────────────────────────────────────────
const censusDoc = {
  generated:   new Date().toISOString(),
  bot:         'organism-alpha-bot',
  totalBots:   KNOWN_BOTS.length,
  healthy,
  degraded,
  unknownBots,
  fleet:       census,
};

fs.writeFileSync(path.join(DOCS, 'fleet-census.json'), JSON.stringify(censusDoc, null, 2));
console.log('✅ Fleet census written → docs/fleet-census.json');
